### ISSUE TITLE
ERR! code ENOVERSIONS

### ISSUE THREAD

**Issue by samzol** [DataTables/Vue#1]
I got this error when I did:

npm install --save datatables.net-vue

Error Codes:

npm ERR! code ENOVERSIONS
npm ERR! No versions available for datatables.net-vue

**Comment by AllanJard** [comment]
You need to use:

```
npm install --save datatables.net-vue3
```

The blog post had it wrong in a few places and right in others - sorry about that. Fixed on the site now.
