### ISSUE TITLE
How to access $.fn.dataTable

### ISSUE THREAD

**Issue by LittleLama** [DataTables/Vue#17]
Hi,
I'm trying to set custom sorting functions as this example. 
https://datatables.net/blog/2016-12-22#How-it-works

It worked when DataTables required to initialise jQuery from window, but since the v2 API I cannot set absolute sorting anymore.

Here like I would have done this.
https://codesandbox.io/s/datatables-option-api-example-with-sorting-ce8i5z?file=/src/App.vue

**Comment by AllanJard** [comment]
Could you post future support requests in the DataTables forums please? It is just easier for me to track support and means everything is in a single searchable place.

I don't see any sorting code in the linked example. Is the question how to add it in?

**Comment by LittleLama** [comment]
Okay, closing issue and posting on the forum. Thanks
