### ISSUE TITLE
Referenced File Not Included

### ISSUE THREAD

**Issue by DaveyJake** [DataTables/Vue#21]
To the DataTables team, on **Line 17** of `datatables.net-vue.vue`, it references `dtEvents.ts` as an import.  The only issue is that actual file is not actually included after running `npm install --save datatables.net-vue3`.

I've copied the file and manually added to my install but just wanted to make sure you all were aware.

Cheers from the States,

Davey

**Comment by DaveyJake** [comment]
It's mostly **VSCode** complaining that there is a "problem" whenever I view the actual `Types` that's the issue. Other than that, there really isn't any problems.  It's mostly integrating `Editor` with `Vue` that's giving me headaches but that's to be expected in the web dev world.

**Comment by AllanJard** [comment]
Embaressing how long its taken me to sort this out - sorry! I've included the dtEvents.ts file in the npm package now, which will hopefully address this issue. Just tagged and released 2.1.2. Its running [nicely here](https://stackblitz.com/edit/datatables-net-vue3-ajax?file=package.json%2Csrc%2FApp.vue).
