### ISSUE TITLE
Nuxt 3 TypeScript Error window is not defined

### ISSUE THREAD

**Issue by geofany** [DataTables/Vue#22]
hello i'm using
`"nuxt": "^3.5.2"`
and
`"datatables.net-vue3": "^2.1.1"`

i'm using data tables like this in my components
<img width="464" alt="Screenshot 2023-06-16 at 22 18 51" src="https://github.com/DataTables/Vue/assets/37582643/8a421b38-313c-4aa2-9581-3f95a9c559f2">

but it got error when i run the project
<img width="1043" alt="Screenshot 2023-06-16 at 22 17 28" src="https://github.com/DataTables/Vue/assets/37582643/23b91f9b-6ab4-4889-8d86-03df6c56ad3d">

**Comment by AllanJard** [comment]
Can you create a mini repo for me showing the error please?

While you are using ESM style imports, something is converting that back to CommonJS which might be causing the issue.

**Comment by geofany** [comment]
> Can you create a mini repo for me showing the error please?
> 
> While you are using ESM style imports, something is converting that back to CommonJS which might be causing the issue.

Sure, 
here's the repo
https://github.com/geofany/nuxt3-datatables

i'm Using 
`Node 18.16.0`
and 
`Yarn`

**Comment by MohanadAlrefaai** [comment]
@geofany You can temporary fix the issue by surrounding the component with ClientOnly tag

**Comment by AllanJard** [comment]
Sorry for the delay in replying here! I had inverted logic in the CommonJS loader when checking for a windowed environment. Doh! [Fix committed here](https://github.com/DataTables/DataTablesSrc/commit/aee2e431a978a1ec5e653b00b3ae71894646307b).

I'll tag 1.13.6 which will have this fix next week.
