### ISSUE TITLE
Custom component not rendering inside responsive dropdown

### ISSUE THREAD

**Issue by BayBreezy** [DataTables/Vue#31]
Hey @AllanJard, 

I noticed that when rendering custom buttons inside the table it gets converted to a weird object when the `responsive` option is set to `true`.

If the column with the button gets placed inside the responsive dropdown it says `[object HTMLDivElement]`. Here is an image

![image](https://github.com/DataTables/Vue/assets/53905713/af1be205-8f0e-4f2b-8cb4-9d2b9afe6adc)

**Comment by AllanJard** [comment]
Have you tried using the `listHiddenNodes()` renderer? https://datatables.net/extensions/responsive/examples/child-rows/original-nodes.html

That, I think, will resolve this.

**Comment by BayBreezy** [comment]
Ohhhhhhhh!!!! Spot on!

Thank you @AllanJard  ❤️ 

P.S: The type of `renderer` need some updating. I get this Typescript error when I follow the docs
```ts
Type 'ResponsiveRenderer' is not assignable to type '(api: Api<any>, rowIdx: number, columns: ResponsiveColumn) => false | Node'.
  Types of parameters 'columns' and 'columns' are incompatible.ts(2322)
  ```

I just put a `//@ts-ignore` over it for now. but it works like a charm.
