### ISSUE TITLE
update datatables option after mount doesn't work

### ISSUE THREAD

**Issue by Bennit99** [DataTables/Vue#37]
Hi DataTables Team,

I would like to add checkbox selection from this [example](https://datatables.net/extensions/select/examples/checkbox/order.html) to my DataTable.

With Vue, the API is only available after mount, so I couldn't define dt.render.select() in the options because dt is not defined yet. I tried updating the options after the components are mounted, but even though the options object is updated, the table doesn't apply the changed options, even after manually reloading the table.

Here is a [StackBlitz example](https://stackblitz.com/edit/vitejs-vite-2l2ptq?file=src%2FApp.vue) demonstrating this issue.

Can you help me resolve this error?

**Comment by AllanJard** [comment]
In that example use: `render: DataTablesCore.render.select(),`.

The `.render.select()` method is a static method on the object exported by `datatables.net`. You've got that called `DataTablesCore` so `DataTablesCore.render.select()` is the way to access it. Not on the `dt` variable.
