### ISSUE TITLE
How to include datetime extension with searchbuilder in vue?

### ISSUE THREAD

**Issue by ajmcgrail** [DataTables/Vue#39]
Hey there. I was trying to make an example of a different problem I was having, but came across this issue while creating the stackblitz where it says that it needs datetime in order to use searchbuilder. But even if I install and import datetime, it doesn't seem to make the error go away.

The stackblitz can be found [here](https://stackblitz.com/edit/datatables-net-vue3-simple-nudaq4?file=src%2FApp.vue). Hopefully I'm just doing something wrong, and feel free to let me know if I should post this on the other forum.

I also partially wanted to see if filter options would be included if the column was recognized as a date- since that was the problem I was originally having and wanted to solve.

**Comment by AllanJard** [comment]
You can use:

```js
DataTablesCore.use(DateTime);
```

to tell DataTables core about the externally loaded package. In an ES Module environment DateTime doesn't automatically attach itself to the DataTablesCore object, as it doesn't actually have a dependency on DataTables.

I had to update the modules (particularly the datatables.net-vue3 one) to their latest versions to get it to work correctly. [Updated stackbltiz](https://stackblitz.com/edit/datatables-net-vue3-simple-jawchy?file=package.json%2Csrc%2FApp.vue).
