### ISSUE TITLE
Where to locate full documentation?

### ISSUE THREAD

**Issue by murugappanrm** [DataTables/Vue#7]
HI,

This is a wonderful extension to vuejs unfortunately it falls short in documentation. Example, I need to configure the styling for bulma and i could not get any help. I find the documentation given by datatables.net is specifically for javascript. 

Where can I get the documentation?

**Comment by AllanJard** [comment]
There is no additional documentation for this plug-in over and above the DataTables general documentation, with the exception of [the blog post](https://datatables.net/blog/2022-06-22-vue) introducing it.

If you want to use Bulma styling for DataTables install the `datatables.net-bm` package. See [the DataTabloes download](//datatables.net/download).
