### ISSUE TITLE
Add custom headers for AJAX request

### ISSUE THREAD

**Issue by swilla** [DataTables/Vue#8]
Is there a way to add headers to the ajax requests? Previously the default JQuery settings appended them, but when I switch to this package they are not appended to the request.

**Comment by AllanJard** [comment]
It might be using a different instance of jQuery? Try `DataTables.use(jQuery)` (or whatever your local jQuery is). Or do:

```js
ajax: {
  url: ...,
  headers: {
   ...
  }
}
```

in your DataTable initialisation.

**Comment by swilla** [comment]
Perfect, exactly what I needed. Thank you!
